spring.application.name=Primo Progetto
spring.datasource.url=jdbc:mysql://localhost:3306/testjpa
spring.datasource.password=password
spring.datasource.username=root

#mostra alcune query di hibernate
spring.jpa.show-sql=true

#inizializza sempre il db  
spring.sql.init.mode=always

#ad ogni avvio del programma viene ricreato il db
spring.jpa.hibernate.ddl-auto=create

#esegue gli insert dopo il create
spring.jpa.defer-datasource-initialization=true